import random 

# function to generate random strings

def randStringGen(stringlength):
    keys = "abcdefghijklmnopqrstuvwxyz " # i left a space after the complete alphabet to signify that the alphabet will be used to generate just a word
    result = ""

    for i in range(stringlength):
        result += keys[random.randrange(27)]

    return result

#this is a function to compare the string generated by the previous function to our goal by scoring it , then the highest scored will be displayed

def stringComparator(generatedString,goalString):
    numSame = 0
    for i in range(len(generatedString)):
        if generatedString[i] == goalString[i]:
            numSame = numSame + 1

    return int((numSame/len(goalString))*100)   #this calculation returns and nteger with 0-100

# this main function will call randStringGen so that it generates a random string with a users desired string length as parameter after which it will take the string generated and compae it to our goal string, and if it scores higher than any of it iteration it will display the result and continue to the next string if any

def main():
    goalString = "approximation"
    generatedString = randStringGen(13)
    score = stringComparator(goalString,generatedString)
    highScore = 0


# you can use any of the while statements below to obtain results

# while statement 1

    # while highScore < 100:
    #     if score > highScore:
    #         highScore = score
    #         print(generatedString)
    #     else:
    #         generatedString = randStringGen(13)
    #         score = stringComparator(goalString,generatedString)



# in this while statement you can play with the IF statement within it to obtain a particular score for the generated string before the loop ends 

# while statement 2

    while True:
        generatedString = randStringGen(13)
        score = stringComparator(goalString,generatedString)
        print(generatedString,score)
        if score >= 20:    
            print(generatedString)
            break
        



main()